# Generated by Django 5.2 on 2026-01-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_hermano', models.IntegerField(unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fec_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hermanos/')),
                ('cargo_junta', models.BooleanField(default=False)),
                ('tipo_hermano', models.CharField(choices=[('Costalero', 'Costalero'), ('Nazareno', 'Nazareno'), ('Tambor', 'Tambor'), ('Protector', 'Protector')], default='Protector')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.rol')),
            ],
            options={
                'db_table': 'rol_reservado',
                'unique_together': {('hermano', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='hermano',
            name='roles',
            field=models.ManyToManyField(blank=True, through='users.RolReservado', to='eventos.rol'),
        ),
    ]
