# Generated by Django 5.2 on 2025-12-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id_hermano', models.AutoField(primary_key=True, serialize=False)),
                ('numero_hermano', models.IntegerField(unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fec_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hermanos/')),
                ('cargo_junta', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHermano',
            fields=[
                ('id_tipo_hermano', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
