# Generated by Django 5.2 on 2026-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='fec_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='tipo_hermano',
            field=models.CharField(blank=True, choices=[('Costalero', 'Costalero'), ('Nazareno', 'Nazareno'), ('Tambor', 'Tambor'), ('Protector', 'Protector')], default='Protector'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
