# Generated by Django 5.2 on 2025-12-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermano',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='tipohermano',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipohermano',
            name='id_tipo_hermano',
        ),
        migrations.RemoveField(
            model_name='tipohermano',
            name='nombre',
        ),
        migrations.AddField(
            model_name='hermano',
            name='tipo_hermano',
            field=models.CharField(choices=[('Costalero', 'Costalero'), ('Nazareno', 'Nazareno'), ('Tambor', 'Tambor'), ('Protector', 'Protector')], default='Protector'),
        ),
        migrations.AddField(
            model_name='tipohermano',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='cargo_junta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/hermanos/'),
        ),
    ]
