# Generated by Django 5.2 on 2025-12-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_acto_foto'),
        ('users', '0002_remove_hermano_nombre_remove_hermano_primer_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='hermanos/'),
        ),
        migrations.CreateModel(
            name='RolReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hermano')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.rol')),
            ],
            options={
                'db_table': 'rol_reservado',
                'unique_together': {('hermano', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='hermano',
            name='roles',
            field=models.ManyToManyField(blank=True, through='users.RolReservado', to='eventos.rol'),
        ),
    ]
