# Generated by Django 5.2 on 2026-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_hermano_fec_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
