# Generated by Django 5.2 on 2026-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_hermano_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoHermano',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='activo',
        ),
        migrations.AlterField(
            model_name='hermano',
            name='tipo_hermano',
            field=models.CharField(blank=True, choices=[('Costalero', 'Costalero'), ('Nazareno', 'Nazareno'), ('Tambor', 'Tambor'), ('Protector', 'Protector')], default='Protector', max_length=20),
        ),
    ]
