services:
  web:
    build: .
    volumes:
      - ./pro_caida/scripts_docker:/code/scripts_docker
      - ./pro_caida:/code
    environment:
      - ENVIRONMENT=development
  nginx:
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./pro_caida:/code
  
  migrate_static:
    build: .
    user: root
    command: sh /code/scripts_docker/dev/web_migrate.sh
    volumes:
      - ./pro_caida:/code
    environment:
      - MAKEMIGRATIONS=yes
      - MIGRATE=yes
      - STATIC=yes
      - ENVIRONMENT=development
    secrets:
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - backend