services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    environment:
      - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    ports:
      - "8000:8000"
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - SECRET_KEY
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    command: sh /code/scripts_docker/dev/web_wait_postgres.sh
    networks:
      - frontend
      - backend
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    networks:
      - frontend
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/postgres_password.txt
  POSTGRES_USER:
    file: ./secrets/postgres_user.txt
  POSTGRES_DB:
    file: ./secrets/postgres_db.txt
  SECRET_KEY:
    file: ./secrets/secret_key.txt