services:
  web:
    image: albertomarmar/caidaelche:latest
    environment:
      - ENVIRONMENT=production
    command: sh /code/scripts_docker/prod/web_wait_postgres.sh

  nginx:
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - certs-data:/data/letsencrypt
      - certs:/etc/letsencrypt
      - static_data:/code/staticfiles
      - media_data:/code/media

  # certbot:
  #   image: certbot/certbot
  #   volumes:   
  #     - certs:/etc/letsencrypt
  #     - certs-data:/data/letsencrypt
  #   command: >
  #     certonly --webroot -w /data/letsencrypt -d lacaidaelche.online -d www.lacaidaelche.online --non-interactive --force-renewal --agree-tos -m albertomarjr5@gmail.com
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == caidaVPS
  #     restart_policy:
  #       condition: none
  
  migrate_static:
    image: albertomarmar/caidaelche:latest
    environment:
      - ENVIRONMENT=production
      - MIGRATE=yes
    command: sh /code/scripts_docker/prod/web_migrate.sh
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - SECRET_KEY
    networks:
      - backend
    deploy:
      mode: replicated-job
      replicas: 1

configs:
  nginx_conf:
    file: ./nginx/prod/nginx.conf

networks:
  frontend:
  backend:
  
volumes:
  certs:
  certs-data:
  static_data:
  media_data:
    