# Generated by Django 5.2 on 2026-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acto',
            fields=[
                ('id_acto', models.AutoField(primary_key=True, serialize=False)),
                ('fec_inicio', models.DateTimeField()),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='actos/')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('protocolo', models.TextField(blank=True, null=True)),
                ('aforo', models.IntegerField(blank=True, null=True)),
                ('limite', models.BooleanField(default=False)),
            ],
        ),
    ]
