# Generated by Django 5.2 on 2025-12-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_acto_imagen'),
        ('users', '0002_remove_hermano_nombre_remove_hermano_primer_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='acto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='acto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/actos/'),
        ),
        migrations.AddField(
            model_name='acto',
            name='id_hermano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hermano'),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('protocolo', models.TextField(blank=True, null=True)),
                ('aforo', models.IntegerField(blank=True, null=True)),
                ('limite', models.BooleanField(default=False)),
                ('id_acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.acto')),
            ],
        ),
    ]
