# Generated by Django 5.2 on 2025-12-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_acto_descripcion_remove_acto_imagen_acto_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='actos/'),
        ),
    ]
