# Generated by Django 5.2 on 2026-02-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='media/galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/noticias')),
            ],
        ),
    ]
